apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-user-api.fullname" . }}
  labels:
{{ include "rest-user-api.labels" . | indent 4 }}
spec:
{{- if .Values.service.type }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rest-user-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
