services:
  db:
    container_name: db
    image: ghcr.io/identicum/mariadb:10
    pull_policy: always
    environment:
     - MARIADB_USER=dbuser
     - MARIADB_PASSWORD=dbpassword
     - MARIADB_ROOT_PASSWORD=rootpwd
     - MARIADB_DATABASE=restusersdb
    ports:
     - "3306:3306"
    restart: always

  rest-users-api:
    container_name: rest-users-api
    image: ghcr.io/identicum/rest-users-api:latest
    # pull_policy: always
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/restusersdb?useSSL=false
    - SPRING_DATASOURCE_USERNAME=dbuser
    - SPRING_DATASOURCE_PASSWORD=dbpassword
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver