version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
     - MYSQL_DATABASE=test
     - MYSQL_ROOT_PASSWORD=password
    ports:
     - "3306:3306"
    restart: always
  rest-users-api:
    container_name: rest-users-api
    image: ghcr.io/identicum/rest-users-api:latest
    ports:
      - 8081:8081
    depends_on:
      - mysql
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
