version: '3'
services:
  rest-users-api:
    container_name: rest-users-api
#   build: .
    image: identicum/rest-users-api
    ports:
      - 8081:8081
    depends_on:
      - users-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://users-db:3306/test?useSSL=false
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
    entrypoint:
        ["/wait-for-it.sh", "users-db:3306", "-s", "--", "java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  users-db:
    container_name: users-db
    image: mysql:5.7
    environment:
     - MYSQL_DATABASE=test
     - MYSQL_ROOT_PASSWORD=password
    ports:
     - "3306:3306"
    restart: always