on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v2
      with:
        debug: true
        languages: ${{ matrix.language }}
    - uses: github/codeql-action/autobuild@v2
    - uses: github/codeql-action/analyze@v2
  build-push:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ghcr.io/identicum/${{github.event.repository.name}}:latest
        context: .
